# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
extensions = Extension.create([{ name: 'Display Updated-At',  download_url: 'https://gist.github.com/roseleaf/e61c877a9c66cfb80e8a/download', short_description: 'Show date an article was updated at, not just created', notes: '**This can be input as markdown!** Terry Richardson pork belly voluptate, Neutra actually before they sold out PBR gluten-free. Stumptown polaroid mixtape High Life fixie. Odio Godard roof party, photo booth officia 
####Terry Richardson
 id exercitation 3 wolf moon delectus. Selfies beard consequat Terry Richardson, asymmetrical minim wayfarers McSweeney\'s Pinterest fixie fashion axe *PBR* cillum Neutra deserunt. Eiusmod sunt pitchfork cardigan odio commodo. Nostrud Carles keffiyeh beard consequat, PBR tattooed sriracha ethnic. Flexitarian hoodie excepteur, exercitation 3 wolf moon freegan trust fund 8-bit seitan commodo Carles Wes Anderson.
', category: 'display', interface: 'classic', author_type: 'services'}, 
	{ name: 'Conditional Fields (Agent)',  download_url: 'https://github.com/zendesk/conditional_fields_app/archive/master.zip', short_description: 'Show and hide fields in the Agent interface', notes: 'dink', category: 'display', interface: 'lotus', author_type: 'services'}, 
	{ name: 'Bitly Integration',  download_url: 'https://github.com/zendesk/bitly_integration_app/archive/master.zip', short_description: 'Shorten any link in your comment with the click of a button', notes: 'This app basically does two things:
Shorten any link by typing it in the text box and clicking shorten.
Reads the existing comment and can convert all existing links to bit.ly links.
Planned Functionality: 
Pull link metrics and display to user.

Lorem go to hizzle check out this fo shizzle mah nizzle fo rizzle, mah home g-dizzle amet, get down get down adipiscing elit. Shut the shizzle up sapizzle velizzle, sure volutpizzle, suscipit quis, gravida vizzle, yo. Pellentesque eget tortizzle. Sed eros. Sure izzle dolizzle break yo neck, yall turpis tempizzle tellivizzle. Maurizzle pellentesque nibh for sure turpizzle. Funky fresh daahng dawg sizzle. Shiznit eleifend rhoncizzle nisi. In gizzle ma nizzle platea dictumst. My shizz fo shizzle. Curabitizzle my shizz fo shizzle mah nizzle fo rizzle, mah home g-dizzle, pretium eu, shizznit shit, fo vitae, nunc. Check it out suscipit. Integizzle sempizzle sizzle crazy.', category: 'comments', interface: 'lotus', author_type: 'services'}, 
	{ name: 'Rebrander',  download_url: 'https://github.com/zendesk/rebrander_app/archive/master.zip', short_description: 'Converts non-branded urls (*.zendesk.com) to branded', notes: 'Etizzle owned magna things crunk yo mamma accumsizzle. Aenizzle izzle own yo\'. Vivamus fo shizzle break yo neck, yall, phat boofron, facilisizzle izzle, the bizzle izzle, crunk. Vestibulum daahng dawg ipsizzle shit izzle break it down crazy luctizzle izzle black posuere shizznit Curae; Fo shizzle dolizzle. Pizzle dope. Maecenas pharetra ma nizzle quizzle. Shiznit rutrizzle aliquizzle shizzle my nizzle crocodizzle. The bizzle facilisis. Sure sizzle nulla, you son of a bizzle eu, scelerisque fo shizzle, blandizzle izzle, magna.', category: 'comments', interface: 'lotus', author_type: 'services'}, 
	{ name: 'Project Management',  download_url: 'https://github.com/zendesk/project_app/archive/master.zip', short_description: 'Create a parent ticket which children tickets are created from', notes: 'Doggy izzle boofron. Fusce magna pimpin\', dignissim sit phat, fringilla egizzle, sollicitudin nec, sure. Maecenizzle a nisi. Sizzle malesuada neque break yo neck, yall risizzle. Suspendisse erat. Ghetto dope tristique turpis. Shut the shizzle up blandizzle ultrices shizzle my nizzle crocodizzle. Sed dolizzle fo shizzle my nizzle, fo shizzle mah nizzle fo rizzle, mah home g-dizzle stuff, posuere ut, dapibus et, fo. Suspendisse we gonna chung tellus. Aenizzle aliquizzle i saw beyonces tizzles and my pizzle went crizzle sit amet dolor. Fusce tellivizzle id arcu. Pimpin\' ipsizzle hizzle sit amet, consectetuer adipiscing elizzle. Suspendisse black shut the shizzle up, eleifend tellivizzle, shizzlin dizzle izzle, brizzle non, elizzle. Mah nizzle that\'s the shizzle rutrum nunc.', category: 'ticket creation', interface: 'lotus', author_type: 'services'}, 
	{ name: 'Create Ticket in Spoke',  download_url: 'https://github.com/zendesk/create_ticket_in_spoke_app/archive/master.zip', short_description: 'Create related ticket from the hub account while in ticket view', notes: 'create ticket in spoke from hub
', category: '', interface: 'lotus', author_type: 'services'},
	{ name: 'Agent Tracker',  download_url: 'https://github.com/zendesk/agent_tracker_app/archive/master.zip', short_description: 'Adds agent name or group to the ticket when the agent views it.', notes: 'gravity-- oxidized imperial, length wort chiller, degrees plato hydrometer hops craft beer. wheat beer glass finishing hops krausen bung; terminal gravity. units of bitterness acid rest terminal gravity, primary fermentation bottom fermenting yeast dry stout? alpha acid, " kolsch carbonation mead bacterial cold filter." real ale brew yeast abbey aau original gravity trappist mash? mash barleywine berliner weisse.', category: 'ticketCreation', interface: 'lotus', author_type: 'services'},
	{ name: 'Facebook Lookup',  download_url: 'https://github.com/zendesk/facebook_lookup_app/archive/master.zip', short_description: 'Lookup users by facebook UID', notes: 'Dawg commodo things izzle urna. Nullizzle congue. Sure viverra laorizzle dui. Check out this bow wow wow amizzle the bizzle eu boom shackalack volutpizzle condimentizzle. Shizznit rizzle. Nunc doggy sizzle stuff purizzle tincidunt aliquizzle. Sizzle gangsta tempizzle ante. Shut the shizzle up interdum erizzle izzle shit. Quisque malesuada. Nizzle shizzlin dizzle tellus sizzle diam mammasay mammasa mamma oo sa viverra. Nulla crackalackin. Nullam shit yippiyo a break yo neck, yall molestie owned. Nullizzle sagittis dui hendrerizzle velit. Break yo neck, yall sempizzle dawg sed doggy. Etizzle pretium purizzle mammasay mammasa mamma oo sa dui. Maecenas rutrum fo shizzle mah nizzle fo rizzle, mah home g-dizzle purus.', category: 'findingData', interface: 'lotus', author_type: 'services'},
	{ name: 'Quick Links App',  download_url: 'https://github.com/zendesk/quicklinks_app/archive/master.zip', short_description: 'Uses data from the ticket to create links that search various websites', notes: 'The quick links app pulls data from the ticket fields to create urls the can open tabs when clicked. http://www.infosniper.net/index.php?ip_address={{ip}}&map_source=1&overview_map=1&lang=1&map_type=1&zoom_level=7 where {{ip}} is a value pulled from a ticket field by the app.js.

carbonation aau ipa: aau brew kettle black malt. lagering, bunghole bottom fermenting yeast terminal gravity lauter, units of bitterness microbrewery saccharification. wit krausen, malt wheat beer glass saccharification squares." bacterial, aerobic gravity cask conditioning mash autolysis.

', category: 'findingData', interface: 'lotus', author_type: 'services'},
	{ name: 'Mobile Customization',  download_url: 'https://gist.github.com/roseleaf/c5dcacfe149b8e653821/download', short_description: 'Mobile optimized styles for web version of zendesk', notes: 'preserve customizability for your portal', category: 'display', interface: 'classic', author_type: 'services'},
	{ name: 'Conditional Fields (End User)',  download_url: 'https://gist.github.com/roseleaf/d062cfb9fa80aada0a73/download', short_description: 'Hide and show certain fields based on conditions', notes: 'the crazy fox jumped over the lazy dog and that is why foxes are better', category: 'display', interface: 'classic', author_type: 'services'}
	]);
